wandb:
  project: multi-task-dt
  entity: marcel98
  model_name: model7

model:
  emb_dim: 256
  dropout: 0.1
  n_layers: 3
  n_heads: 8
  n_actions: 18
  n_rewards: 3
  obs_patch_size: 14
  n_obs_token: 36
  r_low: -20
  r_high: 100
  context_length: 4

train:
  learning_rate: 0.0003
  min_lr_factor: 0.01
  warmup_steps: 8000
  scheduler_steps: 200000
  batch_size: 128
  epochs: 2


ckpt_path: models/breakout4
#start_ckpt: models/breakout4/model-72.pt

